SOAP PL
KlausEB/JavaDesignAndArchitecture pull request #6
Opened 2022-01-25 00:51 UTC by KlausEB

2022-01-25 10:27 UTC, Mazel-Tovr requested changes

2022-01-25 10:27 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/LibrarySOAPService.java
> +    boolean appendAuthor(String authorName);
```suggestion
    boolean addAuthor(String authorName);
```

2022-01-25 10:27 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/LibrarySOAPService.java
> +    boolean appendBook(String authorName,
```suggestion
    boolean addBook(String authorName,
```

2022-01-27 08:05 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/impl/AdminSOAPServiceImpl.java
> +        LibraryService libraryService = LibraryWebWorker.takeLibraryService();
move to class field 
```suggestion
   private LibraryService libraryService = LibraryWebWorker.takeLibraryService();
       
       @Override
    public boolean addNewUser(String login, String password) {
   
```

2022-01-27 09:21 UTC, Mazel-Tovr requested changes

2022-01-27 09:21 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/impl/BookSOAPServiceImpl.java
> +        LibraryService libraryService = LibraryWebWorker.takeLibraryService();
same

2022-01-27 09:21 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/userinterface/CommandsEnum.java
> +    }
What for ? For god's sake delete this ))

2022-01-29 18:32 UTC, Mazel-Tovr requested changes

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/UserAuthorizationChecker.java
> +public class UserAuthorizationChecker {
```suggestion
public class AuthorizationUtil {
```

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/handlers/AdminHandler.java
> +                return libraryService.userIsAdmin(login);
```suggestion
               return UserAuthorizationUtil.isAuthorized(soapMessageContext, Role.Admin);
```

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/handlers/UserHandler.java
> +                return true;
```suggestion
               return UserAuthorizationUtil.isAuthorized(soapMessageContext, Role.values());
```

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/UserAuthorizationChecker.java
> +    public static String authorizeLogin(SOAPMessageContext messageContext) throws SOAPException {
```suggestion
    public static boolean isAuthorized(SOAPMessageContext messageContext, List<Role> roles) throws SOAPException {
```

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/LibraryWebWorker.java
> +}
1. what for this class ? 
2. This is not quite the correct implementation of the singletone pattern.
Check this url
https://stackoverflow.com/questions/18093735/double-checked-locking-in-singleton

2022-01-29 18:32 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/webExceptions/NotAuthorizedException.java
> +}
1. Why runtime ? 
2. on not authorized case we should  throw SOAPFaultException with reason

2022-01-29 18:39 UTC, Mazel-Tovr commented on src/main/resources/history/ActionHistory.txt
>  2021-11-10 01:30:23 - Nikolai:  registration request
it's make sance to add this file to .gitignore

2022-01-29 22:57 UTC, KlausEB commented on src/main/java/com/epam/architecture/SOAPws/handlers/AdminHandler.java
> +                return libraryService.userIsAdmin(login);
I didn't quite understand this point. I need to create a "Role" enumeration and enter its element into the isAuthorized() method, right? And inside isAuthorized() should the user's status be checked based on the enumeration element?

2022-01-30 00:30 UTC, KlausEB commented on src/main/java/com/epam/architecture/SOAPws/util/LibraryWebWorker.java
> +}
The class is needed to work correctly with the LibraryService with preloading data from the database

2022-01-30 12:25 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/LibraryWebWorker.java
> +}
so it's make sance to move this logic to LibraryService class, and add method for example "getInstanceWithDeserializeData" or smth like this

2022-01-30 12:27 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/handlers/AdminHandler.java
> +                return libraryService.userIsAdmin(login);
Yeah, and  in your model class (User) u should to replace boolean flag isAdmin on this Enam

2022-01-30 12:34 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/AuthorizationUtil.java
> +        throw new SOAPFaultException(soapFault);
I don't like this constant 
```
new QName("http://schemas.xmlsoap.org/soap/envelope/", "Client"));
```
so u can replace this on equal code
```suggestion
 SOAPBody soapBody = messageContext..getMessage().getSOAPPart().getEnvelope().getBody();
            SOAPFault soapFault = soapBody.addFault();
            soapFault.setFaultString("Not correct login or password");
            throw new SOAPFaultException(soapFault);
```

2022-01-30 12:36 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/util/LibraryWebWorker.java
> +    private static LibraryService libraryService;
```suggestion
    private static volatile LibraryService libraryService;
```

2022-02-05 15:20 UTC, Mazel-Tovr requested changes

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/handlers/UserHandler.java
> +                return RoleEnum.ADMIN.identifyUserRole(soapMessageContext);
I think it's better to make a separate class, for example, AuthorizationUtil, for authorization, and use the enumeration as a marker
```suggestion
                return AuthorizationUtil.authorize(soapMessageContex, RoleEnum.ADMIN);
```

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/impl/UserSOAPServiceImpl.java
> +    public String getLogin() throws SOAPException {
move to AuthorizationUtil class, and make static 
```suggestion
    public static String getLoginFromRequest(WebServiceContext context) throws SOAPException {
```

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/AdminRole.java
> +public class AdminRole implements LibraryRole {
1. Rename
2. Make all fun static 
```suggestion
public class AuthorizationUtil {
```

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/LibraryRole.java
> +public interface LibraryRole {
no need, remove

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/RoleEnum.java
> +    }
no need
```suggestion
    USER,
    ADMIN;
```

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/UserRole.java
> +public class UserRole implements LibraryRole {
move all to AuthorizationUtil
try to avoid code duplication

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/UserRole.java
> +    public boolean isUserInRole(SOAPMessageContext messageContext) throws SOAPException {
fun name is awful
```suggestion
    public boolean isAuthorizedRequest(SOAPMessageContext messageContext) throws SOAPException {
```

2022-02-05 15:20 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/UserRole.java
> +    public String getAuthorizedUserRole(SOAPMessageContext messageContext) throws SOAPException {
same 
getRole -> return String ???

2022-02-05 15:23 UTC, Mazel-Tovr reviewed
Please, when you fix comment press on 
"Resolve conversation" button, no need to write fixed

2022-02-07 07:48 UTC, Mazel-Tovr requested changes

2022-02-07 07:48 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/roles/AuthorizationUtil.java
> +    }
```suggestion
    public static boolean isAuthorizedRequest(SOAPMessageContext messageContext, Set<RoleEnum> roles) throws SOAPException {
        SOAPHeader soapHeader = messageContext.getMessage().getSOAPHeader();
        Iterator<SOAPHeaderElement> iterator = soapHeader.examineHeaderElements(SOAPConstants.URI_SOAP_ACTOR_NEXT);
        String login = null;
        String password = null;
        while (iterator.hasNext()) {
            Node node = iterator.next();
            if (node.getNodeName().equals("login")) {
                login = node.getValue();
            }
            if (node.getNodeName().equals("password")) {
                password = node.getValue();
            }
        }
        if (login != null && password != null) {
            LibraryService libraryService = LibraryService.getInstanceWithDeserializeData();
            return libraryService.logInAccount(login, password) && roles.contains(libraryService.userRole(login));
        }
        SOAPBody soapBody = messageContext.getMessage().getSOAPPart().getEnvelope().getBody();
        SOAPFault soapFault = soapBody.addFault();
        soapFault.setFaultString("Not correct login or password");
        throw new SOAPFaultException(soapFault);
    }
```

2022-02-07 07:48 UTC, Mazel-Tovr commented on src/main/java/com/epam/architecture/SOAPws/handlers/UserHandler.java
> +                return AuthorizationUtil.isAuthorizedRequest(soapMessageContext, RoleEnum.USER);
Admin also have user rights 
```suggestion
                return AuthorizationUtil.isAuthorizedRequest(soapMessageContext, setOf(RoleEnum.USER,RoleEnum.Admin));
```

2022-02-08 19:52 UTC, Mazel-Tovr approved these changes

2022-02-08 21:04 UTC, merged